# Generated by Django 5.1.6 on 2025-03-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consentlocation_tbl",
            name="enumerator",
        ),
        migrations.RemoveField(
            model_name="farmeridentificationtbl",
            name="consent",
        ),
        migrations.RemoveField(
            model_name="owneridentificationtbl",
            name="farmer_detail",
        ),
        migrations.RemoveField(
            model_name="workerinthefarmtbl",
            name="owner_detail",
        ),
        migrations.AddField(
            model_name="adultinhouseholdtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adult_in_household",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="childinhouseholdtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_in_household",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="childremediationtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_remediation",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="consentlocation_tbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_location",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="endofcollection",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_of_collection",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_identification",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="householdsensitizationtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="household_sensitization",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="owneridentificationtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_identification",
                to="portal.cover_tbl",
            ),
        ),
        migrations.AddField(
            model_name="workerinthefarmtbl",
            name="cover",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_in_farm",
                to="portal.cover_tbl",
            ),
        ),
    ]
