# Generated by Django 5.1.6 on 2025-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_consentlocation_tbl_enumerator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cover_tbl",
            name="enumerator_name",
            field=models.CharField(
                help_text="Enumerator name (letters only, no spaces).", max_length=100
            ),
        ),
    ]
