# Generated by Django 5.1.6 on 2025-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_cover_tbl_enumerator_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cover_tbl",
            name="enumerator_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cover_tbl",
            name="farmer_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cover_tbl",
            name="society_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
