# Generated by Django 5.1.6 on 2025-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0005_alter_consentlocation_tbl_farmer_resides_in_community_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="recruited_workers",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                verbose_name="Have you recruited at least one worker during the past year?",
            ),
        ),
    ]
