# Generated by Django 5.1.6 on 2025-03-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_workerinthefarmtbl_additional_tasks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="additional_tasks",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                verbose_name="Does the worker perform tasks for you or your family members other than those agreed upon?",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="conditions_1",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker is not entitled to move freely.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="conditions_2",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker must be free to communicate with his or her family and friends.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="conditions_3",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker is obliged to adapt to any living conditions imposed by the employer.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="conditions_4",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="It is acceptable for an employer and their family to interfere in a worker's private life.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="conditions_5",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker should not have the freedom to leave work whenever they wish.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="consent_recruitment",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="It is acceptable to recruit someone for work without their consent.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="leaving_1",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker should be required to stay longer than expected while waiting for unpaid salary.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="leaving_2",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker should not be able to leave their employer when they owe money to their employer.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="recruit_1",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="It is acceptable for a person who cannot pay their debts to work for the creditor to reimburse the debt.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="recruit_2",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="It is acceptable for an employer not to reveal the true nature of the work during recruitment.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="recruit_3",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                max_length=2,
                verbose_name="A worker is obliged to work whenever he is called upon by his employer.",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="recruited_workers",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                verbose_name="Have you recruited at least one worker during the past year?",
            ),
        ),
        migrations.AlterField(
            model_name="workerinthefarmtbl",
            name="tasks_clarified",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                verbose_name="Were the tasks to be performed by the worker clarified during recruitment?",
            ),
        ),
    ]
