# Generated by Django 5.1.6 on 2025-03-03 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_workerinthefarmtbl_additional_tasks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workerinthefarmtbl",
            name="cover",
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="additional_tasks",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                default="02",
                verbose_name="Does the worker perform tasks for you or your family members other than those agreed upon?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="conditions_1",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker is not entitled to move freely.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="conditions_2",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker must be free to communicate with his or her family and friends.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="conditions_3",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker is obliged to adapt to any living conditions imposed by the employer.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="conditions_4",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="It is acceptable for an employer and their family to interfere in a worker's private life.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="conditions_5",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker should not have the freedom to leave work whenever they wish.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="consent_recruitment",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="It is acceptable to recruit someone for work without their consent.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="country_origin_owner",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Burkina Faso", "Burkina Faso"),
                    ("Mali", "Mali"),
                    ("Guinea", "Guinea"),
                    ("Ivory Coast", "Ivory Coast"),
                    ("Liberia", "Liberia"),
                    ("Togo", "Togo"),
                    ("Benin", "Benin"),
                    ("Other", "Other"),
                ],
                help_text="If the owner is Non Ghanaian, select the country of origin.",
                max_length=200,
                verbose_name="Country of origin of the owner",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="country_origin_owner_other",
            field=models.CharField(
                blank=True,
                help_text="If 'Other' is selected above, please specify the country.",
                max_length=100,
                verbose_name="Specify country of origin (if Other)",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="first_name_owner",
            field=models.CharField(
                blank=True,
                help_text="Enter the owner's first name. Letters and apostrophes only (no spaces or accents).",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must contain only letters and apostrophes (no spaces or accents).",
                        regex="^[A-Za-z\\']+$",
                    )
                ],
                verbose_name="Owner's First Name",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="leaving_1",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker should be required to stay longer than expected while waiting for unpaid salary.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="leaving_2",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker should not be able to leave their employer when they owe money to their employer.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="manager_work_length",
            field=models.IntegerField(
                default=0,
                verbose_name="For how many years has the respondent been working for the owner?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="name_owner",
            field=models.CharField(
                blank=True,
                help_text="Enter the owner's surname. Letters and apostrophes only (no spaces or accents).",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must contain only letters and apostrophes (no spaces or accents).",
                        regex="^[A-Za-z\\']+$",
                    )
                ],
                verbose_name="Owner's Last Name",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="nationality_owner",
            field=models.CharField(
                choices=[("Ghanaian", "Ghanaian"), ("Non Ghanaian", "Non Ghanaian")],
                default=None,
                max_length=20,
                verbose_name="What is the nationality of the owner?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="recruit_1",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="It is acceptable for a person who cannot pay their debts to work for the creditor to reimburse the debt.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="recruit_2",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="It is acceptable for an employer not to reveal the true nature of the work during recruitment.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="recruit_3",
            field=models.CharField(
                choices=[("01", "Agree"), ("02", "Disagree")],
                default="02",
                max_length=2,
                verbose_name="A worker is obliged to work whenever he is called upon by his employer.",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="recruited_workers",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                default="02",
                verbose_name="Have you recruited at least one worker during the past year?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="refusal_action",
            field=models.CharField(
                choices=[
                    ("Compromise", "I find a compromise"),
                    ("SalaryDeduction", "I withdraw part of their salary"),
                    ("Warning", "I issue a warning"),
                    ("Other", "Other"),
                    ("NotApplicable", "Not applicable"),
                ],
                default="NotApplicable",
                max_length=20,
                verbose_name="What do you do when a worker refuses to perform a task?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="refusal_action_other",
            field=models.CharField(
                blank=True,
                default="NotApplicable",
                help_text="Fill this if 'Other' is selected.",
                max_length=100,
                verbose_name="Specify refusal action",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="salary_status",
            field=models.CharField(
                choices=[
                    ("Always", "Always"),
                    ("Sometimes", "Sometimes"),
                    ("Rarely", "Rarely"),
                    ("Never", "Never"),
                ],
                default="Never",
                max_length=10,
                verbose_name="Do your workers receive their full salaries?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="tasks_clarified",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                default="02",
                verbose_name="Were the tasks to be performed by the worker clarified during recruitment?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="worker_agreement_other",
            field=models.CharField(
                blank=True,
                default="Other",
                help_text="Provide details if 'Other' is selected.",
                max_length=100,
                verbose_name="Specify other agreement type",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="worker_agreement_type",
            field=models.CharField(
                choices=[
                    ("VerbalWithoutWitness", "Verbal agreement without witness"),
                    ("VerbalWithWitness", "Verbal agreement with witness"),
                    ("WrittenWithoutWitness", "Written agreement without witness"),
                    ("WrittenWithWitness", "Written contract with witness"),
                    ("Other", "Other"),
                ],
                default="VerbalWithoutWitness",
                max_length=30,
                verbose_name="What kind of agreement do you have with your workers?",
            ),
        ),
        migrations.AddField(
            model_name="farmeridentificationtbl",
            name="worker_recruitment_type",
            field=models.CharField(
                choices=[("Permanent", "Permanent labor"), ("Casual", "Casual labor")],
                default="Permanent",
                max_length=10,
                verbose_name="Do you recruit workers for...",
            ),
        ),
        migrations.DeleteModel(
            name="OwnerIdentificationTbl",
        ),
        migrations.DeleteModel(
            name="WorkerInTheFarmTbl",
        ),
    ]
