# Generated by Django 5.1.6 on 2025-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_remove_workerinthefarmtbl_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childinhouseholdtbl",
            name="child_can_be_surveyed",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                help_text="Answer Yes if the child is available for survey; No otherwise.",
                verbose_name="Can the child be surveyed now?",
            ),
        ),
        migrations.AlterField(
            model_name="childinhouseholdtbl",
            name="child_declared_in_cover",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                help_text="Yes if the child is already listed in the cover; No otherwise.",
                verbose_name="Is the child among those declared in the cover as the farmer's child?",
            ),
        ),
        migrations.AlterField(
            model_name="childinhouseholdtbl",
            name="children_present",
            field=models.CharField(
                choices=[("01", "Yes"), ("02", "No")],
                help_text="Answer Yes if there are children, No otherwise.",
                verbose_name="Are there children living in the respondent's household?",
            ),
        ),
    ]
